[build]
builder = "dockerfile"
dockerfilePath = "apps/api/Dockerfile"
watchPatterns = ["apps/api/**", "libs/**", "package.json", "nx.json", "tsconfig.base.json", "eslint.config.cjs"]

[deploy]
startCommand = "node main.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
